# Generated by Django 4.2.10 on 2024-03-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_cart_alter_itemdetails_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='descount',
            new_name='discount',
        ),
    ]
